version: "3"

services:
  app:
    hostname: app
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.multistage
    ports:
      - 8080:8080
    networks:
      - default

networks:
  default:
    driver: bridge